Repository knoffhoff/hms, pull requests merged in 2023-06, with the labels that each got.

#1463 fix: different size between "show details" and comment
  hms-app/src/common/styles.ts
  hms-app/src/components/card-details/IdeaCommentDetails.tsx
Labels: frontend, design

#1461 fix: logo and headline colliding
  hms-app/src/common/styles.ts
  hms-app/src/components/HeaderMenu.tsx
Labels: frontend, design

#1477 fix: upload presentation only after hackathon start
  hms-app/src/components/buttons/CardButton.tsx
  hms-app/src/components/card-details/IdeaDetails.tsx
  hms-app/src/components/lists/IdeaCardList.tsx
  hms-app/src/pages/AllIdeas.tsx
  hms-app/src/pages/MyIdeas.tsx
Labels: frontend

#1486 feat: add idea creation date
  hms-app/src/components/card-details/IdeaDetails.tsx
Labels: Bachelor Thesis

#1470 gap between light/dark switch and home is increased
  hms-app/src/components/ThemeSwitchToggle.tsx
Labels: frontend, design

#1492 ba: move idea button is disabled
  hms-app/src/components/MoveIdeaModal.tsx
Labels: Bachelor Thesis

#1495 ba: when MoveModal case hackathons shown without dates
  hms-app/src/components/HackathonSelectDropdown.tsx
Labels: Bachelor Thesis

#1501 move idea button renamed
  hms-app/src/components/MoveIdeaModal.tsx
Labels: Bachelor Thesis

#1506 #1496 ba: descriptions for skills and categories changed
  hms-app/src/components/input-forms/IdeaForm.tsx
Labels: Bachelor Thesis

#1513 #1472 ba: hackathon description visualisation changed
  hms-app/src/components/HackathonHeader.tsx
  hms-app/src/pages/IdeaPool.tsx
Labels: Bachelor Thesis

#1514 fix: new version of button
  hms-app/src/common/colors.ts
  hms-app/src/common/styles.ts
  hms-app/src/components/FinalVideoUploadModal.tsx
  hms-app/src/components/MoveIdeaModal.tsx
  hms-app/src/components/buttons/CardButton.tsx
  hms-app/src/components/buttons/ParticipateButton.tsx
  hms-app/src/components/buttons/VotingButton.tsx
  hms-app/src/components/card-details/IdeaCommentDetails.tsx
  hms-app/src/components/card-details/IdeaDetails.tsx
Labels: Bachelor Thesis

#1522 fix: add headline for hackathon selection
  hms-app/src/components/HackathonSelectDropdown.tsx
  hms-app/src/pages/AllIdeas.tsx
  hms-app/src/pages/Archive.tsx
Labels: Bachelor Thesis

#1532 design: redesign ideacard
  hms-app/src/common/colors.ts
  hms-app/src/common/styles.ts
  hms-app/src/components/FinalVideoUploadModal.tsx
  hms-app/src/components/MoveIdeaModal.tsx
  hms-app/src/components/buttons/CardButton.tsx
  hms-app/src/components/buttons/ParticipateButton.tsx
  hms-app/src/components/buttons/VotingButton.tsx
  hms-app/src/components/card-details/IdeaCommentDetails.tsx
  hms-app/src/components/card-details/IdeaDetails.tsx
Labels: design

#1534 header update for idea pool and hackathons pages
  hms-api/dev/init/hackathon-seed.json
  hms-app/src/common/styles.ts
  hms-app/src/components/HackathonHeader.tsx
  hms-app/src/pages/AllIdeas.tsx
  hms-app/src/pages/Archive.tsx
  hms-app/src/pages/IdeaPool.tsx
Labels: Bachelor Thesis

#1552 #1523 ba: improve notifications
  hms-app/src/components/FinalVideoUploadModal.tsx
  hms-app/src/components/MoveIdeaModal.tsx
  hms-app/src/components/NotificationIcons.tsx
  hms-app/src/components/ParticipantManager.tsx
  hms-app/src/components/VideoDropzone.tsx
  hms-app/src/components/buttons/CardButton.tsx
  hms-app/src/components/buttons/ParticipateButton.tsx
  hms-app/src/components/buttons/VotingButton.tsx
  hms-app/src/components/card-details/HackathonDetails.tsx
  hms-app/src/components/card-details/IdeaCommentDetails.tsx
  hms-app/src/components/input-forms/CategoryForm.tsx
  hms-app/src/components/input-forms/EditUserForm.tsx
  hms-app/src/components/input-forms/HackathonForm.tsx
  hms-app/src/components/input-forms/IdeaForm.tsx
  hms-app/src/components/input-forms/SkillForm.tsx
Labels: Bachelor Thesis
