Repository knoffhoff/hms, pull requests merged in 2023-05, with the labels that each got.

#1389 #1362 & #1364 fix: refresh in user profile & admin page userlist
  hms-app/src/actions/UserActions.tsx
  hms-app/src/components/HeaderMenu.tsx
  hms-app/src/components/card-details/UserDetails.tsx
  hms-app/src/components/input-forms/EditUserForm.tsx
  hms-app/src/components/lists/AllUserList.tsx
  hms-app/src/pages/Layout.tsx
Labels: frontend

#1361 #1352: refactor voting handler
  hms-app/src/components/card-details/HackathonDetails.tsx
  hms-app/src/components/card-details/IdeaCommentDetails.tsx
  hms-app/src/components/card-details/IdeaDetails.tsx
  hms-app/src/components/card-details/ParticipantsHandler.tsx
  hms-app/src/components/card-details/VotingHandler.tsx
Labels: frontend, backend

#1396 1363 fix: empty form and refresh after create hackathon
  hms-app/src/components/input-forms/HackathonForm.tsx
  hms-app/src/components/lists/AllHackathonList.tsx
  hms-app/src/pages/Admin.tsx
Labels: frontend

#1401 #1363 fix: refresh in admin page -> hackathonlist
  hms-app/src/components/card-details/HackathonDetails.tsx
  hms-app/src/components/input-forms/EditUserForm.tsx
  hms-app/src/components/input-forms/HackathonForm.tsx
  hms-app/src/components/lists/AllHackathonList.tsx
Labels: frontend

#1406 #1350 update idea list in the ideation portal when delete idea
  hms-app/src/components/card-details/CardButton.tsx
  hms-app/src/components/card-details/IdeaDetails.tsx
  hms-app/src/components/lists/IdeaCardList.tsx
  hms-app/src/pages/AllIdeas.tsx
  hms-app/src/pages/Archive.tsx
  hms-app/src/pages/IdeationPortal.tsx
  hms-app/src/pages/MyIdeas.tsx
Labels: frontend

#1407 1402 fix: refresh in admin page hackathonlist category
  hms-app/src/components/card-details/CategoryDetails.tsx
  hms-app/src/components/card-details/HackathonDetails.tsx
  hms-app/src/components/input-forms/CategoryForm.tsx
  hms-app/src/components/lists/AllCategoryList.tsx
Labels: frontend

#1410 fix: refresh after delete (admin page hackathonList -> participant list)
  hms-app/src/actions/ParticipantActions.tsx
  hms-app/src/components/card-details/HackathonDetails.tsx
  hms-app/src/components/card-details/ParticipantDetails.tsx
  hms-app/src/components/lists/AllParticipantList.tsx
Labels: frontend

#1356 #1353 & #1354 refactor: idea handler & idea card
  hms-app/src/components/card-details/HackathonDetails.tsx
  hms-app/src/components/card-details/IdeaCommentDetails.tsx
  hms-app/src/components/card-details/IdeaDetails.tsx
  hms-app/src/components/card-details/ParticipantsHandler.tsx
  hms-app/src/components/card-details/VotingHandler.tsx
Labels: help wanted, frontend

#1412 fix: doubled text title in IdeaForm
  hms-app/src/components/input-forms/IdeaForm.tsx
  hms-app/src/pages/AllIdeas.tsx
Labels: frontend

#1415 fix: refresh in admin page skill list
  hms-app/src/components/card-details/SkillDetails.tsx
  hms-app/src/components/input-forms/SkillForm.tsx
  hms-app/src/components/lists/SkillsList.tsx
Labels: frontend

#1419 fix: refresh Hackathons/All Ideas page after deleting an idea
  hms-app/src/pages/AllIdeas.tsx
Labels: frontend

#1421 fix: skills are not loading and not displayed when edit user
  hms-app/src/components/card-details/UserDetails.tsx
  hms-app/src/components/input-forms/EditUserForm.tsx
Labels: frontend

#1424 fix: load chosen skill for idea when edit idea
  hms-app/src/components/input-forms/IdeaForm.tsx
Labels: frontend

#1423 refactor: pass user instead user id to editUserForm
  hms-app/src/components/HeaderMenu.tsx
  hms-app/src/components/card-details/UserDetails.tsx
  hms-app/src/components/input-forms/EditUserForm.tsx
Labels: frontend

#1426 fix: refresh ideation portal after idea is moved
  hms-app/src/components/MoveIdeaModal.tsx
  hms-app/src/components/card-details/CardButton.tsx
Labels: frontend

#1435 fix: refresh in admin page hackathonlist ideas
  hms-app/src/components/MoveIdeaModal.tsx
  hms-app/src/components/card-details/CardButton.tsx
  hms-app/src/components/card-details/HackathonDetails.tsx
  hms-app/src/components/card-details/IdeaDetails.tsx
  hms-app/src/components/card-details/VotingButton.tsx
  hms-app/src/components/input-forms/IdeaForm.tsx
  hms-app/src/components/lists/AllIdeaList.tsx
  hms-app/src/components/lists/IdeaCardList.tsx
  hms-app/src/pages/AllIdeas.tsx
  hms-app/src/pages/IdeationPortal.tsx
  hms-app/src/pages/MyIdeas.tsx
Labels: frontend
